services:
  # 1. BASE DE DONNEES POSTGRESQL
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin_waterflow
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=waterflow_db
    volumes:
      - postgres_waterflow_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_waterflow -d waterflow_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # 2. SERVEUR DE TRACKING MLOPS MLFLOW
  mlflow:
    image: python:3.12-slim
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # Injecte les variables directement ici pour qu'Uvicorn les lise nativement au démarrage
      - UVICORN_PROXY_HEADERS=true
      - UVICORN_FORWARDED_ALLOW_IPS=*
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./mlruns_artifacts:/app/artifacts
    restart: unless-stopped
    command: sh -c "pip install --no-cache-dir mlflow psycopg2-binary && mlflow server --backend-store-uri postgresql://admin_waterflow:${POSTGRES_PASSWORD}@postgres:5432/waterflow_db --default-artifact-root /app/artifacts --host 0.0.0.0 --port 5000"

  # 3. API UNIQUE FASTAPI (Data + Model + OCR)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgresql://admin_waterflow:${POSTGRES_PASSWORD}@postgres:5432/waterflow_db
      # En visant l'adresse IP 127.0.0.1 ou localhost mapée sur le port de la machine hôte, on contourne le DNS Rebinding
      # - MLFLOW_TRACKING_URI=http://172.18.0.1:5000
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - OCR_SPACE_API_KEY=${OCR_SPACE_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_started
    volumes:
      - ./data:/app/data
      - ./mlruns_artifacts:/app/artifacts
      # Force l'injection du code actuel sans passer par le cache de l'image
      - ./src:/app/src
    restart: unless-stopped

  # 4. PIPELINE D'ENTRAÎNEMENT ISOLE
  mlops-training:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops-training
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgresql://admin_waterflow:${POSTGRES_PASSWORD}@postgres:5432/waterflow_db
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_started
    volumes:
      - ./data:/app/data
      - ./mlruns_artifacts:/app/artifacts
    # command: ["python", "-m", "src.experiment"]
    command: sh -c "echo 'Attente initialisation de MLflow...' && sleep 15 && python -m src.experiment"


  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus  # Sauvegarde des métriques
    depends_on:
      - api

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana # Sauvegarde des tableaux de bord
      - ./monitoring/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./monitoring/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./monitoring/dashboard_red.json:/var/lib/grafana/dashboards/dashboard_red.json
      - ./monitoring/alerting.yml:/etc/grafana/provisioning/alerting/alerting.yml


volumes:
  postgres_waterflow_data:
    driver: local
  prometheus_data:
  grafana_data:
