artifact_uri: file:C:/Users/ayoub/Documents/waterflow/mlruns/381877254186828501/dd54d6aea5c24dc6884c03104fd9bfb1/artifacts
end_time: 1779371513420
entry_point_name: ''
experiment_id: '381877254186828501'
lifecycle_stage: active
run_id: dd54d6aea5c24dc6884c03104fd9bfb1
run_name: xgboost
source_name: ''
source_type: 4
source_version: ''
start_time: 1779371511999
status: 3
tags: []
user_id: ayoub
