erDiagram
    CLIENTS {
        varchar client_id PK "Identifiant unique"
        varchar denomination "Nom de la structure"
        text adresse_postale "Adresse physique"
        varchar api_key UK "Clé API hachée (sécurité)"
        varchar role "NOUVEAU : Rôle (client, analyste...)"
    }

    PRELEVEMENTS {
        int id PK "Auto-incrément"
        varchar client_id FK "Référence au propriétaire"
        varchar provenance "Saisie ou OCR"
        varchar lieu "Point de prélèvement"
        float ph ""
        float hardness ""
        float solids ""
        float chloramines ""
        float sulfate ""
        float conductivity ""
        float organic_carbon ""
        float trihalomethanes "ppm"
        float turbidity ""
        int prediction_potability "NOUVEAU : Résultat IA (0/1)"
        varchar model_version "NOUVEAU : Version du modèle"
        text observations ""
        timestamp cree_le "CORRIGÉ : Horodatage"
    }

    ACTION_LOGS {
        int id PK "Auto-incrément"
        varchar client_id "ID ou ANONYMOUS"
        varchar api_key_used "Clé API masquée"
        text endpoint "Route appelée"
        varchar method "GET, POST..."
        int status_code "200, 401, 500..."
        int execution_duration_ms "Temps de réponse"
        timestamp execute_le "Horodatage"
    }

    CLIENTS ||--o{ PRELEVEMENTS : "historise et possède"
    CLIENTS ||--o{ ACTION_LOGS : "génère des logs d'accès"
