name: Drink safe CI


# Actuellement, la CI entraîne les modèles à la volée car le dataset est léger (3276 lignes)
# et le serveur MLflow est conteneurisé localement.
# Si nous devions passer à l'échelle sur des millions de lignes, je ferais évoluer l'architecture :
# je déploierais le serveur MLflow et le stockage des artefacts (S3) sur le Cloud.
# La CI logicielle cesserait d'entraîner et se contenterait de télécharger le modèle distant pour ses tests,
# tandis que l'entraînement ferait l'objet d'un pipeline asynchrone distinct (Continuous Training).


# DÉCLENCHEMENT DU ROBOT à chaque 'push' ou 'pull request' sur n'importe quelle branche
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]


jobs:
  # ======== CI ==========
  tests-pytest:

    runs-on: ubuntu-latest

    steps:

      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Configuration de Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installation des dépendances
        run: uv sync --frozen

      # Recrée l'environnement avec de fausses variables pour les tests
      - name:  Création de l'environnement de Test (.env)
        shell: bash
        run: |
          echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env
          echo "OCR_SPACE_API_KEY=helloworld" >> .env
          echo "SECRET_KEY=TestSecretKey" >> .env
          echo "DATABASE_URL=postgresql://admin_waterflow:${{ secrets.DB_PASSWORD }}@postgres:5432/waterflow_db" >> .env

      # Étape F : allume PostgreSQL et MLflow en tâche de fond (Docker)
      - name: Lancement de l'infrastructure Docker (BDD & MLflow)
        run: |
          docker compose up -d postgres mlflow
          echo "Attente de 15s pour l'initialisation de MLflow..."
          sleep 15

          echo "Entraînement des modèles MLOps (requis pour les tests de non-régression)..."
          docker compose up mlops-training

          echo "Lancement de l'API..."
          docker compose up -d api
          sleep 10

      # - name: Exécution des tests (PyTest)
      # # Surcharge d'env : écrase les variables d'environnement uniquement pour l'étape de Pytest
      # # pour forcer le runner GitHub à utiliser son propre localhost (où les ports Docker sont exposés).
      #   env:
      #     DATABASE_URL: "postgresql://admin_waterflow:${{ secrets.DB_PASSWORD }}@127.0.0.1:5432/waterflow_db"
      #     MLFLOW_TRACKING_URI: "http://127.0.0.1:5000"

      # # Lance les tests
      #   run: uv run pytest -v
      - name: Exécution des tests et calcul de la couverture (PyTest & pytest-cov)
        # Surcharge d'env : force le runner GitHub à utiliser son propre localhost
        # et indique où trouver le code source (PYTHONPATH)
        env:
          DATABASE_URL: "postgresql://admin_waterflow:${{ secrets.DB_PASSWORD }}@127.0.0.1:5432/waterflow_db"
          MLFLOW_TRACKING_URI: "http://127.0.0.1:5000"
          PYTHONPATH: "." 
        # Lance les tests avec le rapport de couverture dans le terminal et en XML
        run: uv run pytest --cov=src --cov-report=term-missing --cov-report=xml tests/



  # ======== CD ==========
  # deploy:
  #   needs: tests-pytest # Ne s'exécute QUE si le job de test a réussi
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' # Uniquement sur la branche principale

  #   steps:
  #     - name: Déploiement sur le VPS via SSH
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{ secrets.VPS_HOST }}
  #         username: ${{ secrets.VPS_USER }}
  #         key: ${{ secrets.VPS_SSH_KEY }}
  #         script: |
  #           cd /chemin/vers/votre/projet/waterflow
  #           git pull origin main
  #           docker compose up -d --build api
